######################## default configuration ####################
baseURL = "/"
title = "Marc-Anthony Bauer"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # disable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45


############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "about/"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog/"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 4

[[menu.main]]
name = "Interesting Things"
URL = "interesting/"
weight = 5

# only desktop menu
[[menu.desktop]]
name = "Contact"
URL = "contact/"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "This is meta description"
author = "Marc-Anthony Bauer"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "Hey, I'm Marc-Anthony!"
image = "images/2020-landscape-1-2.png"

# blog
[params.blog]
heading = "I am a Computational Linguist and Software Engineer. I am passionate about building systems at the intersection of computer science and human languages."

# call to action
[params.call_to_action]
enable = true
title = "Get in contact for more information."
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "Contact Us"
button_url = "contact/"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "About This Site"
content = "This website is a personal project of mine. It's still a work in progress, but I'm expecting everything to be done by the end fo the year. I'm open for work. If you're interested in hiring me, please [reach out](mailto:hi@marcanthonybauer.com)."
copyright = "Copyright &copy; 2021 a hugo theme by [themefisher](https://themefisher.com/hugo-themes/) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"

############################# social site ########################
[params.social]
github = "https://github.com/marcderbauer"
email = "hello@marcanthonybauer.com"
linkedin = "https://www.linkedin.com/in/marcanthonybauer"
